/// Tipos de datos SQL soportados por NexusDB.
/// La implementación completa de Value estará en nexusdb-types.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum DataType {
    Bool,
    TinyInt,
    SmallInt,
    Int,
    BigInt,
    HugeInt,
    UTinyInt,
    USmallInt,
    UInt,
    UBigInt,
    Real,
    Double,
    Decimal { precision: u8, scale: u8 },
    Char(u32),
    VarChar(u32),
    Text,
    CiText,
    Bytes,
    Date,
    Time,
    TimeTz,
    Timestamp,
    TimestampTz,
    Interval,
    Uuid,
    Inet,
    Cidr,
    MacAddr,
    Json,
    Jsonb,
    Vector(u32),
    Array(Box<DataType>),
    Enum(String),
    Range(Box<DataType>),
    Composite(String),
}
