//! Phase 24.1c — `GENERATED ALWAYS|BY DEFAULT AS IDENTITY` integration tests.
//!
//! Covers SQL:2003 identity column semantics:
//! - ALWAYS: explicit INSERT values rejected; NULL/missing auto-generate.
//! - BY DEFAULT: explicit values accepted; NULL/missing auto-generate.
//! - INT and BIGINT identity columns.
//! - Options clause (`(START WITH ...)`) parsed and ignored.
//! - SHOW COLUMNS + SHOW CREATE TABLE display the correct identity syntax.
//! - Existing AUTO_INCREMENT columns continue to display "auto_increment".

mod common;

use axiomdb_sql::{bloom::BloomRegistry, QueryResult, SessionContext};
use axiomdb_storage::MemoryStorage;
use axiomdb_types::Value;
use axiomdb_wal::TxnManager;

use common::*;

fn setup() -> (MemoryStorage, TxnManager, BloomRegistry, SessionContext) {
    setup_ctx()
}

fn run_ok(
    sql: &str,
    storage: &mut MemoryStorage,
    txn: &mut TxnManager,
    bloom: &mut BloomRegistry,
    ctx: &mut SessionContext,
) -> QueryResult {
    run_ctx(sql, storage, txn, bloom, ctx)
        .unwrap_or_else(|e| panic!("SQL failed: {sql}\nError: {e:?}"))
}

fn rows(
    sql: &str,
    storage: &mut MemoryStorage,
    txn: &mut TxnManager,
    bloom: &mut BloomRegistry,
    ctx: &mut SessionContext,
) -> Vec<Vec<Value>> {
    match run_ok(sql, storage, txn, bloom, ctx) {
        QueryResult::Rows { rows, .. } => rows,
        other => panic!("expected rows, got {other:?}"),
    }
}

#[test]
fn always_identity_basic_autoincrement() {
    let (mut storage, mut txn, mut bloom, mut ctx) = setup();

    run_ok(
        "CREATE TABLE t (id INT GENERATED ALWAYS AS IDENTITY, v TEXT)",
        &mut storage,
        &mut txn,
        &mut bloom,
        &mut ctx,
    );
    run_ok(
        "INSERT INTO t(v) VALUES ('a')",
        &mut storage,
        &mut txn,
        &mut bloom,
        &mut ctx,
    );
    run_ok(
        "INSERT INTO t(v) VALUES ('b')",
        &mut storage,
        &mut txn,
        &mut bloom,
        &mut ctx,
    );

    let result = rows(
        "SELECT id, v FROM t ORDER BY id",
        &mut storage,
        &mut txn,
        &mut bloom,
        &mut ctx,
    );
    assert_eq!(result.len(), 2);
    assert_eq!(result[0][0], Value::Int(1));
    assert_eq!(result[1][0], Value::Int(2));
}

#[test]
fn always_identity_rejects_explicit_value() {
    let (mut storage, mut txn, mut bloom, mut ctx) = setup();

    run_ok(
        "CREATE TABLE t (id INT GENERATED ALWAYS AS IDENTITY, v TEXT)",
        &mut storage,
        &mut txn,
        &mut bloom,
        &mut ctx,
    );

    let err = run_ctx(
        "INSERT INTO t(id, v) VALUES (42, 'x')",
        &mut storage,
        &mut txn,
        &mut bloom,
        &mut ctx,
    )
    .expect_err("INSERT with explicit value should be rejected");
    let msg = format!("{err:?}");
    assert!(
        msg.contains("GENERATED ALWAYS AS IDENTITY"),
        "error should mention identity kind: {msg}"
    );
}

#[test]
fn always_identity_accepts_null_as_auto() {
    let (mut storage, mut txn, mut bloom, mut ctx) = setup();

    run_ok(
        "CREATE TABLE t (id INT GENERATED ALWAYS AS IDENTITY, v TEXT)",
        &mut storage,
        &mut txn,
        &mut bloom,
        &mut ctx,
    );
    run_ok(
        "INSERT INTO t(id, v) VALUES (NULL, 'x')",
        &mut storage,
        &mut txn,
        &mut bloom,
        &mut ctx,
    );

    let result = rows(
        "SELECT id, v FROM t",
        &mut storage,
        &mut txn,
        &mut bloom,
        &mut ctx,
    );
    assert_eq!(result.len(), 1);
    assert_eq!(result[0][0], Value::Int(1));
}

#[test]
fn always_identity_on_bigint_column() {
    let (mut storage, mut txn, mut bloom, mut ctx) = setup();

    run_ok(
        "CREATE TABLE t (id BIGINT GENERATED ALWAYS AS IDENTITY, v TEXT)",
        &mut storage,
        &mut txn,
        &mut bloom,
        &mut ctx,
    );
    run_ok(
        "INSERT INTO t(v) VALUES ('big')",
        &mut storage,
        &mut txn,
        &mut bloom,
        &mut ctx,
    );

    let result = rows(
        "SELECT id FROM t",
        &mut storage,
        &mut txn,
        &mut bloom,
        &mut ctx,
    );
    assert_eq!(result[0][0], Value::BigInt(1));
}

#[test]
fn by_default_accepts_explicit_value() {
    let (mut storage, mut txn, mut bloom, mut ctx) = setup();

    run_ok(
        "CREATE TABLE t (id INT GENERATED BY DEFAULT AS IDENTITY, v TEXT)",
        &mut storage,
        &mut txn,
        &mut bloom,
        &mut ctx,
    );
    run_ok(
        "INSERT INTO t(id, v) VALUES (100, 'explicit')",
        &mut storage,
        &mut txn,
        &mut bloom,
        &mut ctx,
    );

    let result = rows(
        "SELECT id, v FROM t",
        &mut storage,
        &mut txn,
        &mut bloom,
        &mut ctx,
    );
    assert_eq!(result.len(), 1);
    assert_eq!(result[0][0], Value::Int(100));
    assert_eq!(result[0][1], Value::Text("explicit".into()));
}

#[test]
fn by_default_autoincrement_on_null() {
    let (mut storage, mut txn, mut bloom, mut ctx) = setup();

    run_ok(
        "CREATE TABLE t (id INT GENERATED BY DEFAULT AS IDENTITY, v TEXT)",
        &mut storage,
        &mut txn,
        &mut bloom,
        &mut ctx,
    );
    run_ok(
        "INSERT INTO t(v) VALUES ('auto')",
        &mut storage,
        &mut txn,
        &mut bloom,
        &mut ctx,
    );
    run_ok(
        "INSERT INTO t(id, v) VALUES (NULL, 'also-auto')",
        &mut storage,
        &mut txn,
        &mut bloom,
        &mut ctx,
    );

    let result = rows(
        "SELECT id FROM t ORDER BY id",
        &mut storage,
        &mut txn,
        &mut bloom,
        &mut ctx,
    );
    assert_eq!(result.len(), 2);
    assert_eq!(result[0][0], Value::Int(1));
    assert_eq!(result[1][0], Value::Int(2));
}

#[test]
fn options_clause_ignored() {
    let (mut storage, mut txn, mut bloom, mut ctx) = setup();

    // Options inside parentheses are parsed but silently ignored;
    // sequence still starts at 1 with increment 1.
    run_ok(
        "CREATE TABLE t (\
            id INT GENERATED ALWAYS AS IDENTITY (START WITH 100 INCREMENT BY 10), \
            v TEXT\
        )",
        &mut storage,
        &mut txn,
        &mut bloom,
        &mut ctx,
    );
    run_ok(
        "INSERT INTO t(v) VALUES ('x')",
        &mut storage,
        &mut txn,
        &mut bloom,
        &mut ctx,
    );

    let result = rows(
        "SELECT id FROM t",
        &mut storage,
        &mut txn,
        &mut bloom,
        &mut ctx,
    );
    assert_eq!(result[0][0], Value::Int(1)); // not 100 — options are ignored
}

#[test]
fn show_columns_always_identity() {
    let (mut storage, mut txn, mut bloom, mut ctx) = setup();

    run_ok(
        "CREATE TABLE t (id INT GENERATED ALWAYS AS IDENTITY, v TEXT)",
        &mut storage,
        &mut txn,
        &mut bloom,
        &mut ctx,
    );

    let result = rows(
        "SHOW COLUMNS FROM t",
        &mut storage,
        &mut txn,
        &mut bloom,
        &mut ctx,
    );
    // Find the `id` row; Extra is the 6th column (index 5).
    let id_row = result
        .iter()
        .find(|r| matches!(&r[0], Value::Text(s) if s == "id"))
        .expect("id column should exist");
    let extra = match &id_row[5] {
        Value::Text(s) => s.as_str(),
        other => panic!("expected text Extra, got {other:?}"),
    };
    assert_eq!(extra, "GENERATED ALWAYS AS IDENTITY");
}

#[test]
fn show_columns_by_default_identity() {
    let (mut storage, mut txn, mut bloom, mut ctx) = setup();

    run_ok(
        "CREATE TABLE t (id INT GENERATED BY DEFAULT AS IDENTITY, v TEXT)",
        &mut storage,
        &mut txn,
        &mut bloom,
        &mut ctx,
    );

    let result = rows(
        "SHOW COLUMNS FROM t",
        &mut storage,
        &mut txn,
        &mut bloom,
        &mut ctx,
    );
    let id_row = result
        .iter()
        .find(|r| matches!(&r[0], Value::Text(s) if s == "id"))
        .expect("id column should exist");
    let extra = match &id_row[5] {
        Value::Text(s) => s.as_str(),
        other => panic!("expected text Extra, got {other:?}"),
    };
    assert_eq!(extra, "GENERATED BY DEFAULT AS IDENTITY");
}

#[test]
fn show_columns_auto_increment_unchanged() {
    let (mut storage, mut txn, mut bloom, mut ctx) = setup();

    // Old MySQL-style AUTO_INCREMENT must keep its previous display string,
    // not the new identity syntax.
    run_ok(
        "CREATE TABLE t (id INT AUTO_INCREMENT PRIMARY KEY, v TEXT)",
        &mut storage,
        &mut txn,
        &mut bloom,
        &mut ctx,
    );

    let result = rows(
        "SHOW COLUMNS FROM t",
        &mut storage,
        &mut txn,
        &mut bloom,
        &mut ctx,
    );
    let id_row = result
        .iter()
        .find(|r| matches!(&r[0], Value::Text(s) if s == "id"))
        .expect("id column should exist");
    let extra = match &id_row[5] {
        Value::Text(s) => s.as_str(),
        other => panic!("expected text Extra, got {other:?}"),
    };
    assert_eq!(extra, "auto_increment");
}

#[test]
fn show_create_table_always_identity() {
    let (mut storage, mut txn, mut bloom, mut ctx) = setup();

    run_ok(
        "CREATE TABLE t (id INT GENERATED ALWAYS AS IDENTITY, v TEXT)",
        &mut storage,
        &mut txn,
        &mut bloom,
        &mut ctx,
    );

    let result = rows(
        "SHOW CREATE TABLE t",
        &mut storage,
        &mut txn,
        &mut bloom,
        &mut ctx,
    );
    let ddl = match &result[0][1] {
        Value::Text(s) => s.clone(),
        other => panic!("expected text DDL, got {other:?}"),
    };
    assert!(
        ddl.contains("GENERATED ALWAYS AS IDENTITY"),
        "DDL should contain identity syntax: {ddl}"
    );
}

#[test]
fn show_create_table_by_default_identity() {
    let (mut storage, mut txn, mut bloom, mut ctx) = setup();

    run_ok(
        "CREATE TABLE t (id BIGINT GENERATED BY DEFAULT AS IDENTITY, v TEXT)",
        &mut storage,
        &mut txn,
        &mut bloom,
        &mut ctx,
    );

    let result = rows(
        "SHOW CREATE TABLE t",
        &mut storage,
        &mut txn,
        &mut bloom,
        &mut ctx,
    );
    let ddl = match &result[0][1] {
        Value::Text(s) => s.clone(),
        other => panic!("expected text DDL, got {other:?}"),
    };
    assert!(
        ddl.contains("GENERATED BY DEFAULT AS IDENTITY"),
        "DDL should contain BY DEFAULT syntax: {ddl}"
    );
}

#[test]
fn always_identity_explicit_zero_treated_as_auto() {
    let (mut storage, mut txn, mut bloom, mut ctx) = setup();

    run_ok(
        "CREATE TABLE t (id INT GENERATED ALWAYS AS IDENTITY, v TEXT)",
        &mut storage,
        &mut txn,
        &mut bloom,
        &mut ctx,
    );
    // Explicit 0 is the MySQL-style auto trigger; for ALWAYS this is
    // treated as "auto-generate" rather than a rejection.
    run_ok(
        "INSERT INTO t(id, v) VALUES (0, 'zero')",
        &mut storage,
        &mut txn,
        &mut bloom,
        &mut ctx,
    );
    let result = rows(
        "SELECT id, v FROM t",
        &mut storage,
        &mut txn,
        &mut bloom,
        &mut ctx,
    );
    assert_eq!(result[0][0], Value::Int(1));
}
